name: Droidian Kali Phosh Manual Build

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Target architecture (arm64, armhf)'
        required: false
        default: 'arm64'
      suite:
        description: 'Debian suite (bookworm, bullseye, etc)'
        required: false
        default: 'bookworm'
      image:
        description: 'Output image file name'
        required: false
        default: 'droidian-kali-phosh.img'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install debos and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debos debootstrap qemu-user-static

      - name: Run debos build
        run: |
          sudo debos \
            -t architecture:${{ github.event.inputs.architecture }} \
            -t suite:${{ github.event.inputs.suite }} \
            -t image:${{ github.event.inputs.image }} \
            droidian-kali-phosh.yaml

      # Optionally, you can upload the built image as an artifact
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.image }}
          path: ${{ github.event.inputs.image }}
