jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kill leftover QEMU/debos processes
        run: |
          pkill -f qemu || true
          pkill -f debos || true

      - name: Remove stale lock files
        run: |
          find /home/runner/work/secret-project/secret-project -name "*.lck" -delete

      - name: Build image with debos
        run: |
          sudo debos \
            --artifactdir /home/runner/work/secret-project/secret-project \
            --template-var architecture:arm64 \
            --template-var suite:bookworm \
            --template-var image:droidian-kali-phosh.img \
            /home/runner/work/secret-project/secret-project/droidian-kali-phosh.yaml \
            --internal-image /dev/disk/by-fakemachine-label/fakedisk-0 \
            --internal-image /dev/disk/by-fakemachine-label/fakedisk-1
