name: Manual Image Build

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Architecture (e.g. arm64, armhf)'
        required: false
        default: 'arm64'
      suite:
        description: 'Debian suite (e.g. bookworm, bullseye)'
        required: false
        default: 'bookworm'
      image_name:
        description: 'Output image name'
        required: false
        default: 'droidian-kali-phosh.img'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove existing image file (prevents QEMU lock error)
        run: rm -f ${{ github.event.inputs.image_name }}

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y debos qemu-user-static debootstrap

      - name: Build image
        run: |
          sudo debos \
            -t architecture:${{ github.event.inputs.architecture }} \
            -t suite:${{ github.event.inputs.suite }} \
            -t image:${{ github.event.inputs.image_name }} \
            droidian-kali-phosh.yaml

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.image_name }}
          path: ${{ github.event.inputs.image_name }}
          if-no-files-found: error
