name: Manual Image Build

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils debos

      # This step ensures no other process is locking the image file
      - name: Ensure no lock on image
        run: |
          fuser -k /home/runner/work/secret-project/secret-project/droidian-kali-phosh.img || true
          rm -f /home/runner/work/secret-project/secret-project/droidian-kali-phosh.img.lock || true

      - name: Build Droidian Kali Phosh image
        run: |
          /debos \
            --artifactdir /home/runner/work/secret-project/secret-project \
            --template-var architecture:arm64 \
            --template-var suite:bookworm \
            --template-var image:droidian-kali-phosh.img \
            /home/runner/work/secret-project/secret-project/droidian-kali-phosh.yaml --internal-i

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: droidian-kali-phosh-img
          path: /home/runner/work/secret-project/secret-project/droidian-kali-phosh.img

      # (Optional) Add more steps as needed for your workflow
